### ISSUE TITLE
Il y a un énorme bug

### ISSUE THREAD

**Issue by sylvainbatte** [BastienGavioli/GitProject#1]
### Attention il y a un gros bug dans l'application

Quand j'utilise la commande clear et bien il y a la lettre "a" qui est ajoutée à mon document. Je ne peux donc pas éditer les différentes fiches de paye de mes employés et ils ne seront donc pas payés

**Comment by BastienGavioli** [comment]
Le gros bug a été corrigé. Merci pour votre signalement
